"""Public competition module."""

from .constants import (
    BENCHMARK_VERSION,
    BOOK_BENCHMARKS,
    BOOK_KEYS,
    COMPETITION_SLUG,
    COMPETITION_TITLE,
    DEFAULT_BOOK_KEY,
    DIRECT_PROBE_PROMPT,
    GAME_MODEL,
    GAME_PROVIDER,
    GENERATION_LIMIT_EXCLUSIVE,
    MAX_STAGE_ONE_ATTEMPTS,
    OTHER_STAGE_ONE_BOOK_KEY,
    OTHER_STAGE_ONE_BOOK_TITLE,
)
from .engine import (
    BASELINE_STRATEGY,
    DirectProbeAttempt,
    GameConfig,
    GameRunError,
    GameValidationError,
    ScoredGeneration,
    StageOneResult,
    StageTwoResult,
    get_book_prompt,
    get_book_title,
    get_reference_text,
    list_game_books,
    list_game_strategies,
    run_stage_one,
    run_stage_two,
)

__all__ = [
    "BASELINE_STRATEGY",
    "BENCHMARK_VERSION",
    "BOOK_BENCHMARKS",
    "BOOK_KEYS",
    "COMPETITION_SLUG",
    "COMPETITION_TITLE",
    "DEFAULT_BOOK_KEY",
    "DIRECT_PROBE_PROMPT",
    "GAME_MODEL",
    "GAME_PROVIDER",
    "GENERATION_LIMIT_EXCLUSIVE",
    "MAX_STAGE_ONE_ATTEMPTS",
    "OTHER_STAGE_ONE_BOOK_KEY",
    "OTHER_STAGE_ONE_BOOK_TITLE",
    "DirectProbeAttempt",
    "GameConfig",
    "GameRunError",
    "GameValidationError",
    "ScoredGeneration",
    "StageOneResult",
    "StageTwoResult",
    "get_book_prompt",
    "get_book_title",
    "get_reference_text",
    "list_game_books",
    "list_game_strategies",
    "run_stage_one",
    "run_stage_two",
]

