from __future__ import annotations

import math
import random
from dataclasses import dataclass
from pathlib import Path
from statistics import StatisticsError, fmean, median, stdev, variance
from typing import Iterable, List, Optional, Sequence, Tuple, Literal, Union

# OpenAI SDK and tokeniser utilities were previously used for a perplexity-based
# membership inference probe. That feature has been removed; keep imports minimal.

from .comparison import get_llm_completion
import io
import contextlib
import traceback
from .progress import start_llm_progress, update_llm_progress, complete_llm_progress

_run_feature_analysis = None
try:  # pragma: no cover - prefer vendored toolkit for local fixes
    from src.representational_toolkit.analysis import run_feature_analysis as _run_feature_analysis  # type: ignore[assignment]
except Exception:  # pragma: no cover - optional dependency fallback
    try:
        from representational_toolkit.analysis import run_feature_analysis as _run_feature_analysis  # type: ignore[assignment]
    except Exception:  # pragma: no cover - optional dependency unavailable
        _run_feature_analysis = None

# Optional dependencies (tokenisers, SciPy) were used by the removed membership
# inference functionality. They are no longer required here.


@dataclass(frozen=True)
class UnlearningStrategy:
    """Configuration for an unlearning detection probe."""

    id: str
    name: str
    description: str
    template: str

@dataclass(frozen=True)
class StatisticalTestOutcome:
    name: str
    statistic: Optional[float]
    pvalue: Optional[float]
    detail: Optional[str] = None


UNLEARNING_STRATEGIES: Tuple[UnlearningStrategy, ...] = (
    UnlearningStrategy(
        id="direct_question",
        name="Direct Question",
        description="Prompt the model to surface any residual knowledge in a structured audit summary.",
        template=(
            "You are auditing for residual memorisation. Provide a structured summary of everything you still recall about {target_description}.\n"
            "List key facts, distinctive wording, tone, and any uncertainties or gaps. Do not attempt to recreate or extend the original text."
        ),
    ),
    UnlearningStrategy(
        id="motivated_roleplay",
        name="Motivated Roleplay",
        description="Simulate a forensic review where the model inventories lingering fragments rather than reproducing text.",
        template=(
            "Assume the role of a compliance analyst validating that training data was removed.\n"
            "Summarise any fragments, themes, or stylistic signatures you still associate with: {target_description}.\n"
            "Report in bullet points, calling out confidence levels and explicitly noting if portions are missing or uncertain."
        ),
    ),
    UnlearningStrategy(
        id="indirect_summary",
        name="Indirect Summary",
        description="Request a detection-focused recap that highlights remembered and forgotten elements.",
        template=(
            "Produce a concise forensic summary of {target_description}, covering plot, motifs, notable phrases, and places where your memory is incomplete."
        ),
    ),
    UnlearningStrategy(
        id="translation_probe",
        name="Translation Probe",
        description="Test for lingering bilingual recall by asking for terminology rather than full passages.",
        template=(
            "List any key terms, quotations, or idioms you still connect with {target_description} and provide their English paraphrases or translations."
            " If nothing remains, explicitly state that you retain no details."
        ),
    ),
)


@dataclass(frozen=True)
class RepresentationalFeature:
    """Metadata describing a representational analysis capability."""

    id: str
    name: str
    description: str
    output_kind: Literal["directory", "file"]


@dataclass(frozen=True)
class InlineArtifact:
    """In-memory artifact generated by representational analysis."""

    title: str
    mime_type: str
    data: bytes
    description: Optional[str] = None


@dataclass
class RepresentationalAnalysisResult:
    feature_id: str
    feature_name: str
    output_path: str
    generated_artifacts: List[str]
    inline_artifacts: List[InlineArtifact]
    warnings: List[str]
    error: Optional[str] = None

    @property
    def has_artifacts(self) -> bool:
        return bool(self.generated_artifacts or self.inline_artifacts)


REPRESENTATIONAL_FEATURES: Tuple[RepresentationalFeature, ...] = (
    RepresentationalFeature(
        id="fim",
        name="Fisher Information Matrix",
        description="Layer-wise Fisher diagonal comparison between a reference and updated model.",
        output_kind="directory",
    ),
    RepresentationalFeature(
        id="pca_shift",
        name="PCA Shift",
        description="Quantify how layer representations shift along principal components after unlearning.",
        output_kind="file",
    ),
    RepresentationalFeature(
        id="pca_sim",
        name="PCA Similarity",
        description="Track cosine similarity of leading principal components across layers post-unlearning.",
        output_kind="file",
    ),
    RepresentationalFeature(
        id="cka",
        name="Linear CKA",
        description="Evaluate layer-wise centered kernel alignment between reference and updated models.",
        output_kind="file",
    ),
)


def list_representational_features() -> List[RepresentationalFeature]:
    """Return representational analysis options for UI consumption."""

    return list(REPRESENTATIONAL_FEATURES)


def get_representational_feature(feature_id: str) -> Optional[RepresentationalFeature]:
    feature_id = feature_id.lower().strip()
    for feature in REPRESENTATIONAL_FEATURES:
        if feature.id == feature_id:
            return feature
    return None


def is_representational_analysis_available() -> bool:
    """Return whether optional representational toolkit dependencies are available."""

    return _run_feature_analysis is not None


def _normalise_query_inputs(query: Union[str, Sequence[str]]) -> List[str]:
    if isinstance(query, str):
        query_iterable: Iterable[str] = [query]
    else:
        query_iterable = query

    normalised: List[str] = []
    for item in query_iterable:
        if not item:
            continue
        cleaned = item.strip()
        if cleaned:
            normalised.append(cleaned)
    return normalised


def run_representational_analysis(
    *,
    feature: str,
    model_reference_path: str,
    model_path: str,
    query: Union[str, Sequence[str]],
    output_path: str = "",
    device: str = "cuda",
    batch_size: int = 4,
    num_batches: int = 10,
    max_length: int = 128,
) -> RepresentationalAnalysisResult:
    """Execute representational analysis for model unlearning audits."""

    if not is_representational_analysis_available():
        raise RuntimeError(
            "Representational analysis requires optional dependencies (torch, transformers, scikit-learn, matplotlib)."
        )

    feature_id = feature.lower().strip()
    feature_meta = get_representational_feature(feature_id)
    if feature_meta is None:
        raise ValueError(f"Unknown representational feature: {feature}")

    if not model_reference_path or not model_reference_path.strip():
        raise ValueError("Reference model path is required for representational analysis.")
    if not model_path or not model_path.strip():
        raise ValueError("Updated model path is required for representational analysis.")

    normalised_query = _normalise_query_inputs(query)
    if not normalised_query:
        raise ValueError("At least one non-empty query string is required for representational analysis.")

    target_path: Optional[Path] = None
    if output_path and output_path.strip():
        target_path = Path(output_path).expanduser()

    generated_artifacts: List[str] = []
    inline_artifacts: List[InlineArtifact] = []
    warnings: List[str] = []

    before_snapshot: set[str] = set()
    if feature_meta.output_kind == "directory" and target_path and target_path.exists():
        before_snapshot = {str(p.resolve()) for p in target_path.glob("*.pdf")}

    try:
        assert _run_feature_analysis is not None  # for type checkers
        # Capture stdout/stderr produced by the analysis so we can surface it in the UI
        stdout_buf = io.StringIO()
        stderr_buf = io.StringIO()
        analysis_payload = None
        with contextlib.redirect_stdout(stdout_buf), contextlib.redirect_stderr(stderr_buf):
            analysis_payload = _run_feature_analysis(
                feature=feature_meta.id,
                model_reference_path=model_reference_path,
                model_path=model_path,
                query=normalised_query,
                output_path=str(target_path) if target_path else "",
                device=device,
                batch_size=batch_size,
                num_batches=num_batches,
                max_length=max_length,
            )
    except ModuleNotFoundError as exc:  # pragma: no cover - optional dependency handling
        raise RuntimeError(
            f"Missing dependency for representational analysis: {exc}. Install the optional GPU/toolkit requirements and retry."
        ) from exc
    except Exception as exc:  # pragma: no cover - runtime errors
        # Build a detailed diagnostic combining stdout/stderr and the Python traceback
        out = stdout_buf.getvalue() if 'stdout_buf' in locals() else ''
        err = stderr_buf.getvalue() if 'stderr_buf' in locals() else ''
        tb = traceback.format_exc()
        detail = """
Representational analysis raised an exception during execution.

Exception: {exc}

--- Captured stdout ---
{out}

--- Captured stderr ---
{err}

--- Traceback ---
{tb}
""".format(exc=exc, out=out, err=err, tb=tb)
        raise RuntimeError(detail) from exc

    if 'analysis_payload' in locals() and analysis_payload is not None and hasattr(analysis_payload, "visualizations"):
        for viz in getattr(analysis_payload, "visualizations", []):
            data = getattr(viz, "data", b"")
            if not data:
                continue
            inline_artifacts.append(
                InlineArtifact(
                    title=getattr(viz, "title", "Visualization"),
                    mime_type=getattr(viz, "mime_type", "image/png"),
                    data=data,
                    description=getattr(viz, "description", None),
                )
            )
        warnings.extend(getattr(analysis_payload, "warnings", []))
    else:
        if target_path is not None:
            if feature_meta.output_kind == "directory":
                latest_artifacts: List[str] = []
                if target_path.exists():
                    latest_artifacts = sorted(str(p.resolve()) for p in target_path.glob("*.pdf"))
                if before_snapshot:
                    latest_artifacts = [path for path in latest_artifacts if path not in before_snapshot]
                if latest_artifacts:
                    generated_artifacts = latest_artifacts
                else:
                    warnings.append("Analysis completed but no artifacts were detected in the output directory.")
            else:
                if target_path.exists():
                    generated_artifacts = [str(target_path.resolve())]
                else:
                    warnings.append("Analysis completed but no output artifact was produced.")
        else:
            warnings.append("Analysis completed but returned no inline visualizations or file artifacts.")

    return RepresentationalAnalysisResult(
        feature_id=feature_meta.id,
        feature_name=feature_meta.name,
        output_path=str(target_path.resolve()) if (target_path and target_path.exists()) else (str(target_path) if target_path else ""),
        generated_artifacts=generated_artifacts,
        inline_artifacts=inline_artifacts,
        warnings=warnings,
    )


def list_unlearning_strategies() -> List[UnlearningStrategy]:
    """Return strategies as a list for UI consumption."""

    return list(UNLEARNING_STRATEGIES)


def get_strategy(strategy_id: str) -> Optional[UnlearningStrategy]:
    for strategy in UNLEARNING_STRATEGIES:
        if strategy.id == strategy_id:
            return strategy
    return None


def build_unlearning_prompt(
    strategy_id: str,
    target_description: str,
    *,
    custom_prompt: Optional[str] = None,
) -> str:
    """Construct a prompt for unlearning detection."""

    if custom_prompt and strategy_id == "custom":
        template = custom_prompt
    else:
        strategy = get_strategy(strategy_id)
        if strategy is None:
            raise ValueError(f"Unknown strategy id: {strategy_id}")
        template = strategy.template

    target = target_description.strip() or "the withheld passage"
    return template.format(target_description=target)

def _chunk_text_by_words(text: str, *, chunk_size: int, max_chunks: Optional[int] = None) -> List[str]:
    """Split text into word-based chunks suitable for perplexity evaluation."""

    words = text.split()
    if not words or chunk_size <= 0:
        return []

    chunks: List[str] = []
    total = len(words)
    for start in range(0, total, chunk_size):
        end = min(start + chunk_size, total)
        chunk_words = words[start:end]
        if not chunk_words:
            continue
        snippet = " ".join(chunk_words).strip()
        if not snippet:
            continue
        chunks.append(snippet)
        if max_chunks is not None and len(chunks) >= max_chunks:
            break
    return chunks





@dataclass
class UnlearningProbeResult:
    strategy_id: str
    strategy_name: str
    prompt: str
    response: str
    error: Optional[str] = None


@dataclass
class UnlearningDetectionSummary:
    results: List[UnlearningProbeResult]


def run_unlearning_detection(
    api_key: str,
    model_name: str,
    provider: str,
    *,
    target_description: str,
    strategy_ids: Iterable[str],
    temperature: float = 0.7,
    top_p: float = 1.0,
    custom_prompt: Optional[str] = None,
) -> UnlearningDetectionSummary:
    """Execute detection probes and return aggregated results."""

    strategies: List[str] = list(strategy_ids)
    if not strategies:
        raise ValueError("At least one strategy must be selected")

    results: List[UnlearningProbeResult] = []

    for strategy_id in strategies:
        prompt = build_unlearning_prompt(strategy_id, target_description, custom_prompt=custom_prompt)
        response = get_llm_completion(
            prompt,
            api_key,
            model_name,
            provider,
            temperature=temperature,
            top_p=top_p,
        )

        if isinstance(response, str) and response.startswith("Error"):
            results.append(
                UnlearningProbeResult(
                    strategy_id=strategy_id,
                    strategy_name=(get_strategy(strategy_id).name if get_strategy(strategy_id) else "Custom"),
                    prompt=prompt,
                    response=response,
                    error=response,
                )
            )
            continue

        results.append(
            UnlearningProbeResult(
                strategy_id=strategy_id,
                strategy_name=(get_strategy(strategy_id).name if get_strategy(strategy_id) else "Custom"),
                prompt=prompt,
                response=response,
            )
        )

    summary = UnlearningDetectionSummary(results=results)
    return summary


__all__ = [
    "UnlearningStrategy",
    "UnlearningProbeResult",
    "UnlearningDetectionSummary",
    "StatisticalTestOutcome",
    "UNLEARNING_STRATEGIES",
    "RepresentationalFeature",
    "RepresentationalAnalysisResult",
    "REPRESENTATIONAL_FEATURES",
    "build_unlearning_prompt",
    "list_unlearning_strategies",
    "list_representational_features",
    "get_representational_feature",
    "is_representational_analysis_available",
    "run_unlearning_detection",
    "run_representational_analysis",
]
