from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, Optional


@dataclass(slots=True)
class VisualizationItem:
    """In-memory artifact generated by representational analysis."""

    title: str
    data: bytes
    mime_type: str = "image/png"
    description: Optional[str] = None


@dataclass(slots=True)
class FeatureAnalysisResult:
    """Container for artefacts produced by an analysis routine."""

    visualizations: List[VisualizationItem] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
