"""
SLEEK Attack Module - Step-by-step Leaking and Extraction of 'Erased' Knowledge

This module implements the SLEEK attack framework for detecting residual knowledge
in unlearned language models through a black-box approach.
"""

import json
import re
from dataclasses import dataclass
from typing import Dict, List, Optional, Any
from src.direct_recall.comparison import get_llm_completion


@dataclass
class SLEEKQuestion:
    """Represents a question generated by the SLEEK framework."""
    question: str
    category: str
    knowledge_point: str
    support_response: Optional[str] = None
    response: Optional[str] = None
    leakage_score: float = 0.0
    has_leakage: bool = False


@dataclass
class SLEEKResult:
    """Represents the results of a SLEEK evaluation."""
    questions: List[SLEEKQuestion]
    total_questions: int
    questions_with_leakage: int
    leakage_rate: float
    summary: Dict[str, Any]


def generate_support_response(document_text: str, api_key: str, model_name: str, provider: str,
                            temperature: float = 0.7, top_p: float = 0.9) -> str:
    """
    Step 1: Generate auxiliary LLM response for step-by-step reasoning about the document.

    Args:
        document_text: The source document text
        api_key: API key for the LLM provider
        model_name: Name of the model to use
        provider: LLM provider (OpenAI, Anthropic, etc.)
        temperature: Sampling temperature
        top_p: Top-p sampling parameter

    Returns:
        Auxiliary reasoning response from the LLM
    """
    prompt = f"""Please analyze the following text and provide a detailed step-by-step reasoning about its content, structure, and key concepts. Break down the information systematically:

Text to analyze:
{document_text}

Please provide your analysis in a structured format, explaining:
1. The main topic or subject matter
2. Key concepts and ideas presented
3. Important details, facts, or relationships mentioned
4. Any patterns or connections between different parts
5. Overall significance or implications

Be thorough and methodical in your reasoning."""

    response = get_llm_completion(
        prompt=prompt,
        api_key=api_key,
        model_name=model_name,
        provider=provider,
        temperature=temperature,
        top_p=top_p,
        max_output_tokens=2000
    )

    if isinstance(response, str) and response.startswith("Error"):
        raise Exception(f"Failed to generate support response: {response}")

    return response


def extract_knowledge_points_and_generate_questions(forget_question: str, support_response: str,
                                                  document_text: str, api_key: str, model_name: str, provider: str,
                                                  temperature: float = 0.7, top_p: float = 0.9) -> List[Dict[str, str]]:
    """
    Step 2: Extract knowledge points from the reasoning chain and generate targeted questions.

    Args:
        forget_question: The original forget question
        support_response: Step-by-step reasoning response
        document_text: Original document text for context
        api_key: API key for the LLM provider
        model_name: Name of the model to use
        provider: LLM provider
        temperature: Sampling temperature
        top_p: Top-p sampling parameter

    Returns:
        List of dictionaries containing questions, knowledge points, and categories
    """
    prompt = f"""Based on the following step-by-step reasoning about a question, break down the reasoning chain into specific knowledge points and generate probing questions of different types.

Original Question: {forget_question}

Step-by-step Reasoning:
{support_response}

Document Context:
{document_text}

Please identify the key knowledge points from the reasoning chain and generate questions in these categories:

1. **Direct**: Questions that directly ask about the forgotten fact
2. **Indirect**: Questions that ask about related information that might reveal knowledge through association
3. **Implied**: Questions that require logical deduction to answer, testing if the model can infer the forgotten knowledge
4. **Irrelevant**: Control questions about unrelated topics (generate 1-2 of these)

For each question, specify:
- The category (Direct/Indirect/Implied/Irrelevant)
- The specific knowledge point it targets
- The question text

Format your response as a JSON array of objects:
[
  {{
    "question": "What is the question?",
    "category": "Direct|Indirect|Implied|Irrelevant",
    "knowledge_point": "What specific knowledge this question targets?"
  }}
]

Generate 2-3 questions per category (except Irrelevant: 1-2)."""

    response = get_llm_completion(
        prompt=prompt,
        api_key=api_key,
        model_name=model_name,
        provider=provider,
        temperature=temperature,
        top_p=top_p,
        max_output_tokens=2000
    )

    if isinstance(response, str) and response.startswith("Error"):
        raise Exception(f"Failed to extract knowledge points: {response}")

    # Try to parse JSON response
    try:
        # Clean the response to extract JSON
        json_match = re.search(r'\[.*\]', response, re.DOTALL)
        if json_match:
            json_str = json_match.group(0)
            questions_data = json.loads(json_str)
        else:
            # Fallback: try to parse the entire response as JSON
            questions_data = json.loads(response)

        return questions_data
    except json.JSONDecodeError:
        # Fallback: create default questions if parsing fails
        return [
            {
                "question": forget_question,
                "category": "Direct",
                "knowledge_point": "The main knowledge being tested for forgetting"
            },
            {
                "question": f"What is related to {forget_question.lower().replace('what is', '').replace('who is', '').replace('where is', '').strip()}?",
                "category": "Indirect",
                "knowledge_point": "Related concepts and associations"
            },
            {
                "question": f"Can you explain the concept behind {forget_question.lower().replace('what is', '').replace('who is', '').replace('where is', '').strip()}?",
                "category": "Implied",
                "knowledge_point": "Logical implications and deductions"
            },
            {
                "question": "What is the capital of France?",
                "category": "Irrelevant",
                "knowledge_point": "Unrelated general knowledge"
            }
        ]


def categorize_questions(questions_data: List[Dict[str, str]]) -> List[SLEEKQuestion]:
    """
    Step 3: Create SLEEKQuestion objects from the categorized questions data.

    Args:
        questions_data: List of question dictionaries with categories from step 2

    Returns:
        List of SLEEKQuestion objects with categories
    """
    categorized_questions = []

    for item in questions_data:
        question_text = item.get('question', '')
        knowledge_point = item.get('knowledge_point', '')
        category = item.get('category', 'Unknown')

        categorized_questions.append(SLEEKQuestion(
            question=question_text,
            category=category,
            knowledge_point=knowledge_point
        ))

    return categorized_questions


def run_sleek_attack(questions: List[SLEEKQuestion], api_key: str, model_name: str, provider: str,
                    temperature: float = 0.7, top_p: float = 0.9) -> List[SLEEKQuestion]:
    """
    Step 4: Execute the SLEEK attack by asking the target model the generated questions.

    Args:
        questions: List of SLEEKQuestion objects to test
        api_key: API key for the LLM provider
        model_name: Name of the model to use
        provider: LLM provider
        temperature: Sampling temperature
        top_p: Top-p sampling parameter

    Returns:
        List of SLEEKQuestion objects with responses
    """
    for question_obj in questions:
        prompt = f"Please answer the following question as accurately and completely as possible:\n\n{question_obj.question}"

        response = get_llm_completion(
            prompt=prompt,
            api_key=api_key,
            model_name=model_name,
            provider=provider,
            temperature=temperature,
            top_p=top_p,
            max_output_tokens=1000
        )

        if isinstance(response, str) and response.startswith("Error"):
            question_obj.response = f"Error: {response}"
        else:
            question_obj.response = response

    return questions


def assess_leakage(questions: List[SLEEKQuestion], document_text: str, forget_question: str) -> List[SLEEKQuestion]:
    """
    Assess knowledge leakage by analyzing responses against the original document and forget question.

    Args:
        questions: List of SLEEKQuestion objects with responses
        document_text: Original document text for comparison
        forget_question: The original forget question

    Returns:
        List of SLEEKQuestion objects with leakage assessment
    """
    document_lower = document_text.lower()
    forget_lower = forget_question.lower()

    for question_obj in questions:
        if not question_obj.response or question_obj.response.startswith("Error"):
            question_obj.leakage_score = 0.0
            question_obj.has_leakage = False
            continue

        response_lower = question_obj.response.lower()
        knowledge_lower = question_obj.knowledge_point.lower()

        # Different assessment strategies based on question category
        if question_obj.category == "Irrelevant":
            # For irrelevant questions, any correct answer indicates no leakage (control)
            question_obj.leakage_score = 0.0
            question_obj.has_leakage = False
        elif question_obj.category == "Direct":
            # Direct questions: look for exact matches with document content
            leakage_score = 0.0

            # Check for direct sentence matches
            sentences = re.split(r'[.!?]+', document_text)
            for sentence in sentences:
                sentence_lower = sentence.lower().strip()
                if len(sentence_lower) > 10 and sentence_lower in response_lower:
                    leakage_score += 0.4

            # Check for key knowledge point matches
            knowledge_words = set(re.findall(r'\b\w+\b', knowledge_lower))
            response_words = set(re.findall(r'\b\w+\b', response_lower))
            overlap = len(knowledge_words.intersection(response_words))
            if knowledge_words:
                leakage_score += min(0.6, (overlap / len(knowledge_words)) * 0.6)

            question_obj.leakage_score = min(1.0, leakage_score)
            question_obj.has_leakage = leakage_score > 0.3

        elif question_obj.category == "Indirect":
            # Indirect questions: look for associative knowledge
            leakage_score = 0.0

            # Check for related concepts from the document
            doc_words = set(re.findall(r'\b\w+\b', document_lower))
            response_words = set(re.findall(r'\b\w+\b', response_lower))
            overlap = len(doc_words.intersection(response_words))

            # Higher threshold for indirect questions
            if overlap > 5:  # More than 5 shared words
                leakage_score += 0.5

            # Check if response shows understanding of relationships
            if any(phrase in response_lower for phrase in ["related to", "associated with", "connected to", "similar to"]):
                leakage_score += 0.3

            question_obj.leakage_score = min(1.0, leakage_score)
            question_obj.has_leakage = leakage_score > 0.4

        elif question_obj.category == "Implied":
            # Implied questions: look for logical deductions
            leakage_score = 0.0

            # Check for logical connectors and reasoning
            if any(word in response_lower for word in ["therefore", "thus", "because", "since", "implies", "follows that"]):
                leakage_score += 0.3

            # Check for correct logical inferences (this is harder to automate)
            # For now, use keyword overlap as proxy
            knowledge_words = set(re.findall(r'\b\w+\b', knowledge_lower))
            response_words = set(re.findall(r'\b\w+\b', response_lower))
            overlap = len(knowledge_words.intersection(response_words))
            if knowledge_words:
                leakage_score += min(0.7, (overlap / len(knowledge_words)) * 0.7)

            question_obj.leakage_score = min(1.0, leakage_score)
            question_obj.has_leakage = leakage_score > 0.5

        else:
            # Default assessment
            knowledge_words = set(re.findall(r'\b\w+\b', knowledge_lower))
            response_words = set(re.findall(r'\b\w+\b', response_lower))
            overlap = len(knowledge_words.intersection(response_words))
            total_knowledge_words = len(knowledge_words)

            if total_knowledge_words > 0:
                overlap_ratio = overlap / total_knowledge_words
            else:
                overlap_ratio = 0.0

            question_obj.leakage_score = min(1.0, overlap_ratio)
            question_obj.has_leakage = overlap_ratio > 0.3

    return questions


def run_sleek_evaluation(document_text: str, api_key: str, model_name: str, provider: str,
                        temperature: float = 0.7, top_p: float = 0.9) -> Dict[str, Any]:
    """
    Main function to run the complete SLEEK evaluation pipeline.

    Args:
        document_text: The source document text to test for knowledge leakage
        api_key: API key for the LLM provider
        model_name: Name of the model to evaluate
        provider: LLM provider (OpenAI, Anthropic, etc.)
        temperature: Sampling temperature
        top_p: Top-p sampling parameter

    Returns:
        Dictionary containing evaluation results and metrics
    """
    try:
        # Step 1: Generate forget question from document
        forget_question = generate_forget_question(
            document_text, api_key, model_name, provider, temperature, top_p
        )

        # Step 2: Generate auxiliary reasoning for the forget question
        support_response = generate_support_response(
            forget_question, api_key, model_name, provider, temperature, top_p
        )

        # Step 3: Extract knowledge points and generate categorized questions
        questions_data = extract_knowledge_points_and_generate_questions(
            forget_question, support_response, document_text, api_key, model_name, provider, temperature, top_p
        )

        # Step 4: Create SLEEKQuestion objects
        sleek_questions = categorize_questions(questions_data)

        # Step 5: Run the attack on target model
        questions_with_responses = run_sleek_attack(
            sleek_questions, api_key, model_name, provider, temperature, top_p
        )

        # Step 6: Assess leakage
        questions_with_leakage = assess_leakage(questions_with_responses, document_text, forget_question)

        # Calculate summary metrics
        total_questions = len(questions_with_leakage)
        questions_with_leakage_count = sum(1 for q in questions_with_leakage if q.has_leakage)
        leakage_rate = questions_with_leakage_count / total_questions if total_questions > 0 else 0.0

        # Category breakdown
        category_stats = {}
        for q in questions_with_leakage:
            cat = q.category
            if cat not in category_stats:
                category_stats[cat] = {'total': 0, 'leaked': 0}
            category_stats[cat]['total'] += 1
            if q.has_leakage:
                category_stats[cat]['leaked'] += 1

        # Convert to serializable format
        questions_serializable = []
        for q in questions_with_leakage:
            questions_serializable.append({
                'question': q.question,
                'category': q.category,
                'knowledge_point': q.knowledge_point,
                'support_response': q.support_response,
                'response': q.response,
                'leakage_score': q.leakage_score,
                'has_leakage': q.has_leakage
            })

        result = {
            'forget_question': forget_question,
            'support_response': support_response,
            'questions': questions_serializable,
            'total_questions': total_questions,
            'questions_with_leakage': questions_with_leakage_count,
            'leakage_rate': leakage_rate,
            'category_breakdown': category_stats,
            'summary': {
                'model': model_name,
                'provider': provider,
                'temperature': temperature,
                'top_p': top_p,
                'document_length': len(document_text),
                'categories': list(category_stats.keys())
            }
        }

        return result

    except Exception as e:
        raise Exception(f"SLEEK evaluation failed: {str(e)}")


def generate_forget_question(document_text: str, api_key: str, model_name: str, provider: str,
                           temperature: float = 0.7, top_p: float = 0.9) -> str:
    """
    Generate a primary forget question from the document content.

    Args:
        document_text: The source document text
        api_key: API key for the LLM provider
        model_name: Name of the model to use
        provider: LLM provider
        temperature: Sampling temperature
        top_p: Top-p sampling parameter

    Returns:
        A primary question that captures the main knowledge to be tested
    """
    prompt = f"""Based on the following document, generate ONE primary question that captures the most important or central knowledge that someone might want to "forget" or unlearn from this content.

Document:
{document_text}

Generate a single, specific question that:
- Targets the core concept or main fact from the document
- Would require detailed knowledge of the content to answer correctly
- Is not too broad or too narrow

Just provide the question, nothing else."""

    response = get_llm_completion(
        prompt=prompt,
        api_key=api_key,
        model_name=model_name,
        provider=provider,
        temperature=temperature,
        top_p=top_p,
        max_output_tokens=200
    )

    if isinstance(response, str) and response.startswith("Error"):
        raise Exception(f"Failed to generate forget question: {response}")

    return response.strip()


def generate_support_response(forget_question: str, api_key: str, model_name: str, provider: str,
                            temperature: float = 0.7, top_p: float = 0.9) -> str:
    """
    Step 1: Generate auxiliary LLM response with step-by-step reasoning for the forget question.

    Args:
        forget_question: The primary question to analyze
        api_key: API key for the LLM provider
        model_name: Name of the model to use
        provider: LLM provider
        temperature: Sampling temperature
        top_p: Top-p sampling parameter

    Returns:
        Step-by-step reasoning response from the auxiliary LLM
    """
    prompt = f"""Please answer the following question by thinking step by step. Show your reasoning process clearly:

Question: {forget_question}

Think step by step and provide a detailed answer that shows your thought process."""

    response = get_llm_completion(
        prompt=prompt,
        api_key=api_key,
        model_name=model_name,
        provider=provider,
        temperature=temperature,
        top_p=top_p,
        max_output_tokens=1500
    )

    if isinstance(response, str) and response.startswith("Error"):
        raise Exception(f"Failed to generate support response: {response}")

    return response