"""
SLEEK Attack Module - Step-by-step Leaking and Extraction of 'Erased' Knowledge

This module implements the SLEEK attack framework for detecting residual knowledge
in unlearned language models through a black-box approach.
"""

import json
import re
from dataclasses import dataclass
from typing import Dict, List, Optional, Any
from src.direct_recall.comparison import get_llm_completion


@dataclass
class SLEEKQuestion:
    """Represents a question generated by the SLEEK framework."""
    question: str
    category: str
    knowledge_point: str
    support_response: Optional[str] = None
    response: Optional[str] = None
    leakage_score: float = 0.0
    has_leakage: bool = False


@dataclass
class SLEEKResult:
    """Represents the results of a SLEEK evaluation."""
    questions: List[SLEEKQuestion]
    total_questions: int
    questions_with_leakage: int
    leakage_rate: float
    summary: Dict[str, Any]


def generate_support_response(document_text: str, api_key: str, model_name: str, provider: str,
                            temperature: float = 0.7, top_p: float = 0.9) -> str:
    """
    Step 1: Generate auxiliary LLM response for step-by-step reasoning about the document.

    Args:
        document_text: The source document text
        api_key: API key for the LLM provider
        model_name: Name of the model to use
        provider: LLM provider (OpenAI, Anthropic, etc.)
        temperature: Sampling temperature
        top_p: Top-p sampling parameter

    Returns:
        Auxiliary reasoning response from the LLM
    """
    prompt = f"""Please analyze the following text and provide a detailed step-by-step reasoning about its content, structure, and key concepts. Break down the information systematically:

Text to analyze:
{document_text}

Please provide your analysis in a structured format, explaining:
1. The main topic or subject matter
2. Key concepts and ideas presented
3. Important details, facts, or relationships mentioned
4. Any patterns or connections between different parts
5. Overall significance or implications

Be thorough and methodical in your reasoning."""

    response = get_llm_completion(
        prompt=prompt,
        api_key=api_key,
        model_name=model_name,
        provider=provider,
        temperature=temperature,
        top_p=top_p,
        max_output_tokens=2000
    )

    if isinstance(response, str) and response.startswith("Error"):
        raise Exception(f"Failed to generate support response: {response}")

    return response


def extract_knowledge_points_and_generate_questions(forget_question: str, support_response: str,
                                                  document_text: str, api_key: str, model_name: str, provider: str,
                                                  temperature: float = 0.7, top_p: float = 0.9) -> List[Dict[str, str]]:
    """
    Step 2: Extract knowledge points from the reasoning chain and generate targeted questions.

    Args:
        forget_question: The original forget question
        support_response: Step-by-step reasoning response
        document_text: Original document text for context
        api_key: API key for the LLM provider
        model_name: Name of the model to use
        provider: LLM provider
        temperature: Sampling temperature
        top_p: Top-p sampling parameter

    Returns:
        List of dictionaries containing questions, knowledge points, and categories
    """
    prompt = f"""Based on the following step-by-step reasoning about a question, break down the reasoning chain into specific knowledge points and generate probing questions of different types.

Original Question: {forget_question}

Step-by-step Reasoning:
{support_response}

Document Context:
{document_text}

Please identify the key knowledge points from the reasoning chain and generate questions in these categories:

1. **Direct**: Questions that directly ask about the forgotten fact
2. **Indirect**: Questions that ask about related information that might reveal knowledge through association
3. **Implied**: Questions that require logical deduction to answer, testing if the model can infer the forgotten knowledge
4. **Irrelevant**: Control questions about unrelated topics (generate 1-2 of these)

For each question, specify:
- The category (Direct/Indirect/Implied/Irrelevant)
- The specific knowledge point it targets
- The question text

Format your response as a JSON array of objects:
[
  {{
    "question": "What is the question?",
    "category": "Direct|Indirect|Implied|Irrelevant",
    "knowledge_point": "What specific knowledge this question targets?"
  }}
]

Generate 2-3 questions per category (except Irrelevant: 1-2)."""

    response = get_llm_completion(
        prompt=prompt,
        api_key=api_key,
        model_name=model_name,
        provider=provider,
        temperature=temperature,
        top_p=top_p,
        max_output_tokens=2000
    )

    if isinstance(response, str) and response.startswith("Error"):
        raise Exception(f"Failed to extract knowledge points: {response}")

    # Try to parse JSON response
    try:
        # Clean the response to extract JSON
        json_match = re.search(r'\[.*\]', response, re.DOTALL)
        if json_match:
            json_str = json_match.group(0)
            questions_data = json.loads(json_str)
        else:
            # Fallback: try to parse the entire response as JSON
            questions_data = json.loads(response)

        return questions_data
    except json.JSONDecodeError:
        # Fallback: create default questions if parsing fails
        return [
            {
                "question": forget_question,
                "category": "Direct",
                "knowledge_point": "The main knowledge being tested for forgetting"
            },
            {
                "question": f"What is related to {forget_question.lower().replace('what is', '').replace('who is', '').replace('where is', '').strip()}?",
                "category": "Indirect",
                "knowledge_point": "Related concepts and associations"
            },
            {
                "question": f"Can you explain the concept behind {forget_question.lower().replace('what is', '').replace('who is', '').replace('where is', '').strip()}?",
                "category": "Implied",
                "knowledge_point": "Logical implications and deductions"
            },
            {
                "question": "What is the capital of France?",
                "category": "Irrelevant",
                "knowledge_point": "Unrelated general knowledge"
            }
        ]


def categorize_questions(questions_data: List[Dict[str, str]]) -> List[SLEEKQuestion]:
    """
    Step 3: Create SLEEKQuestion objects from the categorized questions data.

    Args:
        questions_data: List of question dictionaries with categories from step 2

    Returns:
        List of SLEEKQuestion objects with categories
    """
    categorized_questions = []

    for item in questions_data:
        question_text = item.get('question', '')
        knowledge_point = item.get('knowledge_point', '')
        category = item.get('category', 'Unknown')

        categorized_questions.append(SLEEKQuestion(
            question=question_text,
            category=category,
            knowledge_point=knowledge_point
        ))

    return categorized_questions


def run_sleek_attack(questions: List[SLEEKQuestion], api_key: str, model_name: str, provider: str,
                    temperature: float = 0.7, top_p: float = 0.9) -> List[SLEEKQuestion]:
    """
    Step 4: Execute the SLEEK attack by asking the target model the generated questions.

    Args:
        questions: List of SLEEKQuestion objects to test
        api_key: API key for the LLM provider
        model_name: Name of the model to use
        provider: LLM provider
        temperature: Sampling temperature
        top_p: Top-p sampling parameter

    Returns:
        List of SLEEKQuestion objects with responses
    """
    for question_obj in questions:
        prompt = f"Please answer the following question as accurately and completely as possible:\n\n{question_obj.question}"

        response = get_llm_completion(
            prompt=prompt,
            api_key=api_key,
            model_name=model_name,
            provider=provider,
            temperature=temperature,
            top_p=top_p,
            max_output_tokens=1000
        )

        if isinstance(response, str) and response.startswith("Error"):
            question_obj.response = f"Error: {response}"
        else:
            question_obj.response = response

    return questions


def assess_leakage(questions: List[SLEEKQuestion], document_text: str, forget_question: str) -> List[SLEEKQuestion]:
    """
    Assess knowledge leakage by analyzing responses against the original document and forget question.

    Args:
        questions: List of SLEEKQuestion objects with responses
        document_text: Original document text for comparison
        forget_question: The original forget question

    Returns:
        List of SLEEKQuestion objects with leakage assessment
    """
    document_lower = document_text.lower()
    forget_lower = forget_question.lower()

    for question_obj in questions:
        if not question_obj.response or question_obj.response.startswith("Error"):
            question_obj.leakage_score = 0.0
            question_obj.has_leakage = False
            continue

        response_lower = question_obj.response.lower()
        knowledge_lower = question_obj.knowledge_point.lower()

        # Different assessment strategies based on question category
        if question_obj.category == "Irrelevant":
            # For irrelevant questions, any correct answer indicates no leakage (control)
            question_obj.leakage_score = 0.0
            question_obj.has_leakage = False
        elif question_obj.category == "Direct":
            # Direct questions: look for exact matches with document content
            leakage_score = 0.0

            # Check for direct sentence matches
            sentences = re.split(r'[.!?]+', document_text)
            for sentence in sentences:
                sentence_lower = sentence.lower().strip()
                if len(sentence_lower) > 10 and sentence_lower in response_lower:
                    leakage_score += 0.4

            # Check for key knowledge point matches
            knowledge_words = set(re.findall(r'\b\w+\b', knowledge_lower))
            response_words = set(re.findall(r'\b\w+\b', response_lower))
            overlap = len(knowledge_words.intersection(response_words))
            if knowledge_words:
                leakage_score += min(0.6, (overlap / len(knowledge_words)) * 0.6)

            question_obj.leakage_score = min(1.0, leakage_score)
            question_obj.has_leakage = leakage_score > 0.3

        elif question_obj.category == "Indirect":
            # Indirect questions: look for associative knowledge
            leakage_score = 0.0

            # Check for related concepts from the document
            doc_words = set(re.findall(r'\b\w+\b', document_lower))
            response_words = set(re.findall(r'\b\w+\b', response_lower))
            overlap = len(doc_words.intersection(response_words))

            # Higher threshold for indirect questions
            if overlap > 5:  # More than 5 shared words
                leakage_score += 0.5

            # Check if response shows understanding of relationships
            if any(phrase in response_lower for phrase in ["related to", "associated with", "connected to", "similar to"]):
                leakage_score += 0.3

            question_obj.leakage_score = min(1.0, leakage_score)
            question_obj.has_leakage = leakage_score > 0.4

        elif question_obj.category == "Implied":
            # Implied questions: look for logical deductions
            leakage_score = 0.0

            # Check for logical connectors and reasoning
            if any(word in response_lower for word in ["therefore", "thus", "because", "since", "implies", "follows that"]):
                leakage_score += 0.3

            # Check for correct logical inferences (this is harder to automate)
            # For now, use keyword overlap as proxy
            knowledge_words = set(re.findall(r'\b\w+\b', knowledge_lower))
            response_words = set(re.findall(r'\b\w+\b', response_lower))
            overlap = len(knowledge_words.intersection(response_words))
            if knowledge_words:
                leakage_score += min(0.7, (overlap / len(knowledge_words)) * 0.7)

            question_obj.leakage_score = min(1.0, leakage_score)
            question_obj.has_leakage = leakage_score > 0.5

        else:
            # Default assessment
            knowledge_words = set(re.findall(r'\b\w+\b', knowledge_lower))
            response_words = set(re.findall(r'\b\w+\b', response_lower))
            overlap = len(knowledge_words.intersection(response_words))
            total_knowledge_words = len(knowledge_words)

            if total_knowledge_words > 0:
                overlap_ratio = overlap / total_knowledge_words
            else:
                overlap_ratio = 0.0

            question_obj.leakage_score = min(1.0, overlap_ratio)
            question_obj.has_leakage = overlap_ratio > 0.3

    return questions


def run_sleek_evaluation(document_text: str, api_key: str, model_name: str, provider: str,
                        temperature: float = 0.7, top_p: float = 0.9) -> Dict[str, Any]:
    """
    Main function to run the complete SLEEK evaluation pipeline.

    Args:
        document_text: The source document text to test for knowledge leakage
        api_key: API key for the LLM provider
        model_name: Name of the model to evaluate
        provider: LLM provider (OpenAI, Anthropic, etc.)
        temperature: Sampling temperature
        top_p: Top-p sampling parameter

    Returns:
        Dictionary containing evaluation results and metrics
    """
    try:
        # Step 1: Generate forget question from document
        forget_question = generate_forget_question(
            document_text, api_key, model_name, provider, temperature, top_p
        )

        # Step 2: Generate auxiliary reasoning for the forget question
        support_response = generate_support_response(
            forget_question, api_key, model_name, provider, temperature, top_p
        )

        # Step 3: Extract knowledge points and generate categorized questions
        questions_data = extract_knowledge_points_and_generate_questions(
            forget_question, support_response, document_text, api_key, model_name, provider, temperature, top_p
        )

        # Step 4: Create SLEEKQuestion objects
        sleek_questions = categorize_questions(questions_data)

        # Step 5: Run the attack on target model
        questions_with_responses = run_sleek_attack(
            sleek_questions, api_key, model_name, provider, temperature, top_p
        )

        # Step 6: Assess leakage
        questions_with_leakage = assess_leakage(questions_with_responses, document_text, forget_question)

        # Calculate summary metrics
        total_questions = len(questions_with_leakage)
        questions_with_leakage_count = sum(1 for q in questions_with_leakage if q.has_leakage)
        leakage_rate = questions_with_leakage_count / total_questions if total_questions > 0 else 0.0

        # Category breakdown
        category_stats = {}
        for q in questions_with_leakage:
            cat = q.category
            if cat not in category_stats:
                category_stats[cat] = {'total': 0, 'leaked': 0}
            category_stats[cat]['total'] += 1
            if q.has_leakage:
                category_stats[cat]['leaked'] += 1

        # Convert to serializable format
        questions_serializable = []
        for q in questions_with_leakage:
            questions_serializable.append({
                'question': q.question,
                'category': q.category,
                'knowledge_point': q.knowledge_point,
                'support_response': q.support_response,
                'response': q.response,
                'leakage_score': q.leakage_score,
                'has_leakage': q.has_leakage
            })

        result = {
            'forget_question': forget_question,
            'support_response': support_response,
            'questions': questions_serializable,
            'total_questions': total_questions,
            'questions_with_leakage': questions_with_leakage_count,
            'leakage_rate': leakage_rate,
            'category_breakdown': category_stats,
            'summary': {
                'model': model_name,
                'provider': provider,
                'temperature': temperature,
                'top_p': top_p,
                'document_length': len(document_text),
                'categories': list(category_stats.keys())
            }
        }

        return result

    except Exception as e:
        raise Exception(f"SLEEK evaluation failed: {str(e)}")


def generate_forget_question(document_text: str, api_key: str, model_name: str, provider: str,
                           temperature: float = 0.7, top_p: float = 0.9) -> str:
    """
    Generate a primary forget question from the document content.

    Args:
        document_text: The source document text
        api_key: API key for the LLM provider
        model_name: Name of the model to use
        provider: LLM provider
        temperature: Sampling temperature
        top_p: Top-p sampling parameter

    Returns:
        A primary question that captures the main knowledge to be tested
    """
    prompt = f"""Based on the following document, generate ONE primary question that captures the most important or central knowledge that someone might want to "forget" or unlearn from this content.

Document:
{document_text}

Generate a single, specific question that:
- Targets the core concept or main fact from the document
- Would require detailed knowledge of the content to answer correctly
- Is not too broad or too narrow

Just provide the question, nothing else."""

    response = get_llm_completion(
        prompt=prompt,
        api_key=api_key,
        model_name=model_name,
        provider=provider,
        temperature=temperature,
        top_p=top_p,
        max_output_tokens=200
    )

    if isinstance(response, str) and response.startswith("Error"):
        raise Exception(f"Failed to generate forget question: {response}")

    return response.strip()


def generate_support_response(forget_question: str, api_key: str, model_name: str, provider: str,
                            temperature: float = 0.7, top_p: float = 0.9) -> str:
    """
    Step 1: Generate auxiliary LLM response with step-by-step reasoning for the forget question.

    Args:
        forget_question: The primary question to analyze
        api_key: API key for the LLM provider
        model_name: Name of the model to use
        provider: LLM provider
        temperature: Sampling temperature
        top_p: Top-p sampling parameter

    Returns:
        Step-by-step reasoning response from the auxiliary LLM
    """
    prompt = f"""Please answer the following question by thinking step by step. Show your reasoning process clearly:

Question: {forget_question}

Think step by step and provide a detailed answer that shows your thought process."""

    response = get_llm_completion(
        prompt=prompt,
        api_key=api_key,
        model_name=model_name,
        provider=provider,
        temperature=temperature,
        top_p=top_p,
        max_output_tokens=1500
    )

    if isinstance(response, str) and response.startswith("Error"):
        raise Exception(f"Failed to generate support response: {response}")

    return response


def decompose_question_with_cot(question: str, answer: str, api_key: str, model_name: str, provider: str,
                                temperature: float = 0.7, top_p: float = 0.9) -> List[Dict[str, str]]:
    """
    Decompose a question into sub-questions using Chain of Thought reasoning.
    
    Args:
        question: The original question to decompose
        answer: The ground truth answer for context
        api_key: API key for the LLM provider
        model_name: Name of the model to use
        provider: LLM provider
        temperature: Sampling temperature
        top_p: Top-p sampling parameter
        
    Returns:
        List of sub-questions with categories and expected answers
    """
    prompt = f"""You are tasked with decomposing a question into multiple sub-questions to systematically probe knowledge.

Original Question: {question}
Ground Truth Answer: {answer}

Please decompose this question into 4-6 sub-questions in the following categories:

1. **Direct**: Questions that directly ask about the core fact (1-2 questions)
2. **Indirect**: Questions about related information that might reveal knowledge through association (1-2 questions)  
3. **Implied**: Questions requiring logical deduction to test if the model can infer the knowledge (1-2 questions)

For each sub-question, provide:
- The question text
- The category (Direct/Indirect/Implied)
- The expected answer based on the ground truth

Format your response as a JSON array:
[
  {{
    "question": "Sub-question text?",
    "category": "Direct|Indirect|Implied",
    "expected_answer": "Expected answer based on ground truth"
  }}
]

Only output the JSON array, nothing else."""

    response = get_llm_completion(
        prompt=prompt,
        api_key=api_key,
        model_name=model_name,
        provider=provider,
        temperature=temperature,
        top_p=top_p,
        max_output_tokens=2000
    )

    if isinstance(response, str) and response.startswith("Error"):
        # Return fallback with original question
        return [{
            "question": question,
            "category": "Direct",
            "expected_answer": answer
        }]

    # Parse JSON response
    try:
        json_match = re.search(r'\[.*\]', response, re.DOTALL)
        if json_match:
            json_str = json_match.group(0)
            sub_questions = json.loads(json_str)
        else:
            sub_questions = json.loads(response)
        
        # Validate structure
        validated = []
        for sq in sub_questions:
            if isinstance(sq, dict) and 'question' in sq:
                validated.append({
                    'question': sq.get('question', ''),
                    'category': sq.get('category', 'Direct'),
                    'expected_answer': sq.get('expected_answer', answer)
                })
        
        if validated:
            return validated
            
    except json.JSONDecodeError:
        pass
    
    # Fallback: return original question
    return [{
        "question": question,
        "category": "Direct", 
        "expected_answer": answer
    }]


def run_sleek_qa_evaluation(
    qa_pairs: List[Dict[str, str]],
    api_key: str,
    model_name: str,
    provider: str,
    num_runs: int = 1,
    temperature: float = 0.7,
    top_p: float = 0.9,
    progress_callback=None
) -> Dict[str, Any]:
    """
    Run Step-by-step Leaking and Extraction evaluation on Q/A pairs.
    
    This function:
    1. Decomposes each question into sub-questions using COT
    2. Evaluates each sub-question using the target model
    3. Compares responses with expected answers
    4. Aggregates results by category
    
    Args:
        qa_pairs: List of Q/A pair dictionaries with 'question' and 'answer' keys
        api_key: API key for the LLM provider
        model_name: Name of the model to use
        provider: LLM provider
        num_runs: Number of evaluation runs per sub-question
        temperature: Sampling temperature for evaluation
        top_p: Top-p sampling parameter
        progress_callback: Optional callback for progress updates
        
    Returns:
        Dictionary containing evaluation results
    """
    from src.direct_recall.comparison import calculate_rouge_score, calculate_jaccard_index
    from Levenshtein import distance as levenshtein_distance
    
    all_results = []
    total_sub_questions = 0
    current_progress = 0
    
    # First pass: decompose all questions to count total
    decomposed_pairs = []
    for qa_pair in qa_pairs:
        question = qa_pair.get('question', '')
        answer = qa_pair.get('answer', '')
        
        # Decompose the question
        sub_questions = decompose_question_with_cot(
            question=question,
            answer=answer,
            api_key=api_key,
            model_name=model_name,
            provider=provider,
            temperature=0.7,
            top_p=0.9
        )
        
        decomposed_pairs.append({
            'original_question': question,
            'original_answer': answer,
            'sub_questions': sub_questions
        })
        total_sub_questions += len(sub_questions)
    
    total_items = total_sub_questions * num_runs
    
    # Evaluate each decomposed pair
    for pair_idx, decomposed in enumerate(decomposed_pairs):
        original_question = decomposed['original_question']
        original_answer = decomposed['original_answer']
        sub_questions = decomposed['sub_questions']
        
        pair_results = {
            'original_question': original_question,
            'original_answer': original_answer,
            'sub_question_results': [],
            'category_breakdown': {}
        }
        
        for sq_idx, sub_q in enumerate(sub_questions):
            sq_question = sub_q.get('question', '')
            sq_category = sub_q.get('category', 'Direct')
            sq_expected = sub_q.get('expected_answer', original_answer)
            
            run_results = []
            for run_idx in range(num_runs):
                current_progress += 1
                
                if progress_callback:
                    progress_callback(
                        current_progress,
                        total_items,
                        pair_idx + 1,
                        sq_idx + 1,
                        len(sub_questions)
                    )
                
                # Get LLM response
                prompt = f"Please answer the following question concisely and accurately:\n\nQuestion: {sq_question}\n\nAnswer:"
                
                response = get_llm_completion(
                    prompt=prompt,
                    api_key=api_key,
                    model_name=model_name,
                    provider=provider,
                    temperature=temperature,
                    top_p=top_p,
                    max_output_tokens=500
                )
                
                if isinstance(response, str) and response.startswith("Error"):
                    llm_answer = f"Error: {response}"
                else:
                    llm_answer = response.strip()
                    if llm_answer.lower().startswith("answer:"):
                        llm_answer = llm_answer[7:].strip()
                
                # Calculate metrics
                rouge_score = calculate_rouge_score(sq_expected, llm_answer)
                jaccard = calculate_jaccard_index(sq_expected, llm_answer)
                lev_dist = levenshtein_distance(sq_expected.lower(), llm_answer.lower())
                
                run_results.append({
                    'run': run_idx + 1,
                    'llm_answer': llm_answer,
                    'rouge_score': rouge_score,
                    'jaccard_index': jaccard,
                    'levenshtein_distance': lev_dist
                })
            
            # Aggregate run results
            avg_rouge = sum(r['rouge_score'] for r in run_results) / len(run_results) if run_results else 0
            avg_jaccard = sum(r['jaccard_index'] for r in run_results) / len(run_results) if run_results else 0
            
            # Determine if leakage detected (high similarity indicates memorization)
            has_leakage = avg_rouge > 0.3 or avg_jaccard > 0.3
            
            sq_result = {
                'question': sq_question,
                'category': sq_category,
                'expected_answer': sq_expected,
                'runs': run_results,
                'avg_rouge_score': avg_rouge,
                'avg_jaccard_index': avg_jaccard,
                'has_leakage': has_leakage
            }
            
            pair_results['sub_question_results'].append(sq_result)
            
            # Update category breakdown
            if sq_category not in pair_results['category_breakdown']:
                pair_results['category_breakdown'][sq_category] = {'total': 0, 'leaked': 0, 'avg_rouge': 0, 'avg_jaccard': 0}
            pair_results['category_breakdown'][sq_category]['total'] += 1
            if has_leakage:
                pair_results['category_breakdown'][sq_category]['leaked'] += 1
        
        # Calculate category averages
        for cat, stats in pair_results['category_breakdown'].items():
            cat_results = [r for r in pair_results['sub_question_results'] if r['category'] == cat]
            if cat_results:
                stats['avg_rouge'] = sum(r['avg_rouge_score'] for r in cat_results) / len(cat_results)
                stats['avg_jaccard'] = sum(r['avg_jaccard_index'] for r in cat_results) / len(cat_results)
        
        all_results.append(pair_results)
    
    # Calculate overall statistics
    total_sub_q = sum(len(r['sub_question_results']) for r in all_results)
    total_leaked = sum(
        sum(1 for sq in r['sub_question_results'] if sq['has_leakage'])
        for r in all_results
    )
    
    overall_category_breakdown = {}
    for result in all_results:
        for cat, stats in result['category_breakdown'].items():
            if cat not in overall_category_breakdown:
                overall_category_breakdown[cat] = {'total': 0, 'leaked': 0, 'rouge_sum': 0, 'jaccard_sum': 0}
            overall_category_breakdown[cat]['total'] += stats['total']
            overall_category_breakdown[cat]['leaked'] += stats['leaked']
            overall_category_breakdown[cat]['rouge_sum'] += stats['avg_rouge'] * stats['total']
            overall_category_breakdown[cat]['jaccard_sum'] += stats['avg_jaccard'] * stats['total']
    
    # Finalize category averages
    for cat, stats in overall_category_breakdown.items():
        if stats['total'] > 0:
            stats['avg_rouge'] = stats['rouge_sum'] / stats['total']
            stats['avg_jaccard'] = stats['jaccard_sum'] / stats['total']
            stats['leakage_rate'] = stats['leaked'] / stats['total']
        del stats['rouge_sum']
        del stats['jaccard_sum']
    
    return {
        'qa_pair_results': all_results,
        'total_original_questions': len(qa_pairs),
        'total_sub_questions': total_sub_q,
        'total_with_leakage': total_leaked,
        'overall_leakage_rate': total_leaked / total_sub_q if total_sub_q > 0 else 0,
        'category_breakdown': overall_category_breakdown,
        'summary': {
            'model': model_name,
            'provider': provider,
            'num_runs': num_runs,
            'temperature': temperature,
            'top_p': top_p
        }
    }